name = "sugimoto-blyukher.github.io"
main = "dist/_worker.js/index.js"
compatibility_date = "2025-12-03"  # ← 自分の環境の日付か、少し前の実在日付にする

# Node.js ライクなAPIを使うならほぼ必須
compatibility_flags = ["nodejs_compat"]

[assets]
# Astro がビルドした静的ファイルを置く場所
binding   = "ASSETS"
directory = "./dist"
